name: execute scraping and database loading

on:
  schedule:
    - cron: '50 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
    
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      - name: execute python script
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          DB_NAME: ${{ secrets.DB_NAME }}
          NEWS_COLLECTION_NAME: ${{ secrets.NEWS_COLLECTION_NAME }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python index.py
